### ISSUE TITLE
[BUG] README.adoc has dead links

### ISSUE THREAD

**Issue by jholovacs** [sailpoint-oss/sailpoint-api-guidelines#8]
**Describe the bug**
The README.adoc file has hyperlinks to the guide, but they don't appear to be working. They all appear to give a 404 message.

**To Reproduce**
1. Go to the main page of this repo
2. Scroll down to the README.adoc rendering
3. Click one of the aforementioned links
4. Profit!

**Expected behavior**
I would expect these links to render the documents they seem to indicate.

**Screenshots**
![image](https://user-images.githubusercontent.com/1767540/146043658-28d91bd0-49e9-4961-a10f-05302b9329da.png)
![image](https://user-images.githubusercontent.com/1767540/146044018-412ab8ae-c716-401c-83ac-8d333a3ff8d1.png)

**Comment by tyler-mairose-sp** [comment]
Hello Jeremy, I had a PR for this that I had not yet merged in. Take a look again and please let me know if you can access the links!

**Comment by colin-mckibben-sp** [comment]
This appears to be fixed now
